#!/bin/bash

echo "CHECKING PM2 STATUS AND SERVER LOGS"
echo "==================================="

echo "From your screenshot, I can see PM2 is running with:"
echo "- Process: optistore-production"
echo "- Status: online"
echo "- Memory: 35.8mb"
echo ""
echo "This means the Node.js server IS running!"
echo ""
echo "The 502 error is likely due to:"
echo "1. Nginx proxy configuration issue"
echo "2. Port binding problem"
echo "3. Server listening on wrong interface"
echo ""
echo "SSH COMMANDS TO DEBUG:"
echo "====================="
echo ""
echo "1. Check if server is listening on port 8080:"
echo "   netstat -tlnp | grep 8080"
echo ""
echo "2. Check PM2 logs for errors:"
echo "   pm2 logs optistore-production"
echo ""
echo "3. Test server directly on localhost:"
echo "   curl http://localhost:8080/api/dashboard"
echo ""
echo "4. Check nginx error logs:"
echo "   tail -f /var/log/nginx/error.log"
echo ""
echo "5. If server is running but not accessible, restart with correct binding:"
echo "   pm2 restart optistore-production"
echo ""
echo "The PM2 process is running successfully - we just need to fix the proxy configuration."