#!/bin/bash

echo "EMERGENCY PRODUCTION SERVER RESTART"
echo "==================================="

echo "This script provides the exact commands to run in SSH to restart your production server."
echo ""
echo "SSH COMMANDS TO RUN:"
echo "==================="
echo ""
echo "1. Connect to server:"
echo "   ssh root@5.181.218.15"
echo ""
echo "2. Navigate to project directory:"
echo "   cd /var/www/vhosts/vivaindia.com/opt.vivaindia.sql"
echo ""
echo "3. Check current PM2 status:"
echo "   pm2 status"
echo ""
echo "4. View recent logs:"
echo "   pm2 logs optistore-production --lines 20"
echo ""
echo "5. Force restart the process:"
echo "   pm2 restart optistore-production"
echo ""
echo "6. If process is missing, recreate it:"
echo "   pm2 delete optistore-production"
echo "   DATABASE_URL=\"mysql://ledbpt_optie:g79h94LAP@5.181.218.15:3306/opticpro\" PORT=8080 pm2 start tsx --name optistore-production -- server/index.ts"
echo "   pm2 save"
echo ""
echo "7. Test if server is responding:"
echo "   curl http://localhost:8080/api/dashboard"
echo ""
echo "8. Check if port is listening:"
echo "   netstat -tlnp | grep 8080"
echo ""
echo "EXPECTED SUCCESS OUTPUT:"
echo "- PM2 status shows 'online'"
echo "- curl returns JSON data"
echo "- netstat shows process on port 8080"
echo "- Logs show 'serving on port 8080'"
echo ""
echo "After server is confirmed working, update nginx in Plesk."