#!/bin/bash

# This is the most direct fix for the production server issue

echo "=== IMMEDIATE PRODUCTION FIX ==="
echo ""
echo "Your production server is down. Here's the exact fix:"
echo ""
echo "1. Open SSH terminal to: ssh root@5.181.218.15"
echo "2. Run these commands:"
echo ""
echo "cd /var/www/vhosts/vivaindia.com/opt.vivaindia.sql"
echo "pkill -f tsx"
echo "npm install -g tsx"
echo "DATABASE_URL=\"mysql://ledbpt_optie:g79h94LAP@5.181.218.15:3306/opticpro\" PORT=8080 tsx server/index.ts &"
echo ""
echo "That's it! Your server will be running again."
echo ""
echo "=== PERMANENT SOLUTION ==="
echo "To prevent daily crashes, also install PM2:"
echo ""
echo "npm install -g pm2"
echo "pm2 start \"DATABASE_URL='mysql://ledbpt_optie:g79h94LAP@5.181.218.15:3306/opticpro' PORT=8080 tsx server/index.ts\" --name optistore"
echo "pm2 save"
echo "pm2 startup"
echo ""
echo "PM2 will auto-restart your server if it crashes."